openapi: 3.1.0
info:
  title: Bugpack API
  version: '0.1'

paths:
  /{project_id}/envelope:
    post:
      operationId: Envelope
      parameters:
        - name: Accept-Encoding
          in: header
          schema:
            type: string
            # enum:
            #   - gzip
            #   - identity
        - name: Content-Encoding
          in: header
          schema:
            type: string
            enum:
              - gzip # used with Accept-Encoding: identity
        # sentry.go/0.35.1
        # sentry.python/2.37.0
        - name: User-Agent
          in: header
          schema:
            type: string
        # Sentry sentry_version=7, sentry_client=sentry.go/0.35.1, sentry_key=username
        # Sentry sentry_key=username, sentry_version=7, sentry_client=sentry.python/2.37.0
        - name: X-Sentry-Auth
          in: header
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/x-sentry-envelope:
            schema:
              type: string
              format: binary
  /bugs:
    head:
      operationId: CountBugs
    get:
      operationId: ListBugs
  /bugs/{bug_id}:
    get:
      operationId: GetBug

components:
  parameters:
    # id_offset_32:
    #   name: id_offset
    #   in: query
    #   schema:
    #     type: integer
    #     format: int32
    #   description: Query ID offset (skip objects from start of selection up to this ID)
    # id_offset_64:
    #   name: id_offset
    #   in: query
    #   schema:
    #     type: integer
    #     format: int64
    #   description: Query ID offset (skip objects from start of selection up to this ID)
    # offset:
    #   name: offset
    #   in: query
    #   schema:
    #     type: integer
    #     format: int32
    #     default: 0
    #     minumum: 0
    #     maximum: 200
    #   description: Query offset
    limit:
      name: limit
      in: query
      schema:
        type: integer
        format: int32
        default: 100
        minimum: 1
        maximum: 200
      description: How many objects return in response body

  responses:
    NotFound:
      description: Object not found

    PermissionDenied:
      description: Permission denied

  headers:
    X-Count:
      required: true
      description: Objects count
      schema:
        type: integer
        format: int64

  securitySchemes:
    OAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
